In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr2 = my_arr * 2

Wall time: 45.9 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.02 s


In [7]:
data = np.random.randn(2,3)

In [8]:
data

array([[ 0.51549361, -0.0735319 , -1.34702598],
       [ 1.07600238, -0.57657761, -1.72967335]])

In [9]:
data * 10

array([[  5.15493605,  -0.73531901, -13.47025977],
       [ 10.76002375,  -5.76577611, -17.29673345]])

In [10]:
data + data

array([[ 1.03098721, -0.1470638 , -2.69405195],
       [ 2.15200475, -1.15315522, -3.45934669]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1= [6,7.5,8,0,1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.ndim

2

In [22]:
arr2.dtype

dtype('int32')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.empty((2,3,2))

array([[[8.60656331e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.63132264e+185]],

       [[2.67787343e-032, 1.41565275e-076],
        [1.31425606e-047, 3.12165571e-033],
        [9.05305313e-043, 1.79821876e-052]]])

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr1 = np.array([1,2,3], dtype = np.float64)

In [30]:
arr2 = np.array([1,2,3], dtype = np.float32)

In [31]:
arr1.dtype

dtype('float64')

In [32]:
arr2.dtype

dtype('float32')

In [33]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [34]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [35]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [37]:
numeric_strings = np.array(['1.25','-9.6', '42'], dtype = np.string_)

In [40]:
calibers = np.array([.22,.270,.357,.380,.44,.50], dtype = np.float64)

In [41]:
int_array.astype(calibers.dtype)

NameError: name 'int_array' is not defined

In [42]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])

In [43]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
arr -arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [48]:
arr **0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [50]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [51]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [52]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr[5]

5

In [54]:
arr[5:8]

array([5, 6, 7])

In [55]:
arr_slice = arr[5:8]

In [56]:
arr_slice

array([5, 6, 7])

In [57]:
arr_slice[1] = 12345

In [58]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [59]:
arr_slice[:] = 64

In [60]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [63]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
names = np.array(['Bob', 'Joe', 'will', 'Bob', 'will', 'joe', 'joe'])

In [68]:
data = np.random.randn(7,4)

In [69]:
names

array(['Bob', 'Joe', 'will', 'Bob', 'will', 'joe', 'joe'], dtype='<U4')